### ISSUE TITLE
vless + ws

### ISSUE THREAD

**Issue by 10rino** [MatsuriDayo/NekoBoxForAndroid#115]
Hi My Vless + WebSocket servers do not connect in the program and I receive error
I try #47 but my problem not resolved just error changed
in any utls Except android i got `2023/04/28 06:54:05 ERROR[0004] [947534575 648ms] inbound/tun[tun-in]: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x01\x00\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"`

in android utls i got `2023/04/28 06:59:27 ERROR[0002] [3111488606 442ms] inbound/tun[tun-in]: remote error: tls: protocol version not supported`

My config is connected in other clients without any problem, but in Nekobox does not connect

You have a solution other than #47?

**Comment by EndermanCo** [comment]
It seems that the operating system does not support this version of TLS because the mobile phone is old. If it is tls 1.3, change to tls 1.2 or tls 1.1.

**Comment by 10rino** [comment]
No, I don't think the problem is with the mobile because it is new and has Android 13. I also said that it connects without any problem on other clients such as Matsuri and V2rayng. But on Nekobox it gives me these errors

**Comment by privatesupport** [comment]
Do you use domain as address? if yes, change domain to an IP.
else clean ALPN field of config.

**Comment by 10rino** [comment]
I just clear h2 in ALPN and I tried all uTLS until finally it was connected in Randomized uTLS, thank you bro
