### ISSUE TITLE
文档疑问

### ISSUE THREAD

**Issue by klzgrad** [MatsuriDayo/NekoBoxForAndroid#122]
1. https://matsuridayo.github.io/nb4a-configuration/
> Tun 实现
> 由 sing-box 实现，目前有 gVisor System 两种。

这两种有什么优劣，怎么选取呢？以前问过，但是并没有解答清楚/或者我看不懂 https://github.com/SagerNet/SagerNet/discussions/327 如果这次有关于用户如何选取选项的新说法，可以补充。

2. 
> 对于能使用 Socks / HTTP 代理的应用，建议手动为其设置 Socks / HTTP 代理，不走 Tun 更省电。

这是在说另外一个选项：Inbound Settings里面的Append HTTP Proxy to VPN？

3. Naive的选项里面sni和cert这两个选项是做什么的？NaiveFmt.kt里面处理sni的目的/用途没有看懂。cert似乎原来是通过环境变量配置Root CA？但是没找到这个选项在哪里代码生效的。

**Comment by klzgrad** [comment]
> Naive 的证书可以用 SSL_CERT_FILE 环境变量指定

找到了，在这里生效https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/f5385e1d090735eb7712462e59047da39e33eb13/app/src/main/java/io/nekohasekai/sagernet/bg/proto/BoxInstance.kt#L170 

这个功能的用途在于有些用户希望自行签发证书，但Chrome策略不允许自签名证书，需要用户自行创建Root CA然后再签发证书。我是不太理解为什么要这么费劲地自行签发证书。

> SNI

这个的用途呢？如前，这一段 https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/f5385e1d090735eb7712462e59047da39e33eb13/app/src/main/java/io/nekohasekai/sagernet/fmt/naive/NaiveFmt.kt#L60-L76 没有看出意图

**Comment by klzgrad** [comment]
> Tun 实现

所以“System/gVisor”并不是实现一个tun，因为这个tun已经通过VpnService实现了。这里“System/gVisor”实现的事情应该叫“TCP数据流重组”或者直接叫“TCP stack”，而“System”这个方案有人叫“二次NAT”。

去查先有工作：

有人问过类似问题：
https://github.com/huolizhuminh/NetWorkPacketCapture/issues/46 
https://github.com/mightofcode/android-vpnservice-example/issues/4

可追溯到 2014年 https://github.com/oldman1977/SmartProxy/blob/master/Smart%20Proxy%20X/src/main/java/me/smartproxy/core/LocalVpnService.java#L245

**Comment by wanzhiyu** [comment]
太感谢了，最近在调试singbox的tun模式，发现就算直连都无法上网，我以为是路由表的问题，查了很久也没发现问题。
然后我想起来stack的兼容性问题，于是测试后我发现只能用gvisor而无法使用system，gvisor的速度明显很慢，而且不稳定。
看到大佬的回复才发现是防火墙的问题，允许singbox应用通过防火墙，立马变得飞快，还是system性能好而且靠谱啊，前提是防火墙得给权限通过。
