### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [MatsuriDayo/NekoBoxForAndroid#13]
Hi 👋

Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-03-17-02-11-12-244_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/225768921-2acdb805-2880-46ba-a3f8-965d938ec7c6.jpg)

Thanks 🙏

**Comment by xmha97** [comment]
Any updates?

**Comment by jihuanyu** [comment]
This icon is a matter of the theme pack and has nothing to do with the software. You can modify or add the icon in the theme pack.Of course, you need to make your own icons.

**Comment by xmha97** [comment]
> This icon is a matter of the theme pack and has nothing to do with the software. You can modify or add the icon in the theme pack.Of course, you need to make your own icons.

No, it is a feature of Android 13 (not a icon pack)
https://www.androidpolice.com/android-13-themed-icons-how-to-activate/

**Comment by xmha97** [comment]
> @arm64v8a 这个是否可行？
> 
> SVG是原图，`android-files.zip`是简单[生成](https://brandmark.io/logo-crunch/)的带有背景的像素画。
> 
> ![NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/51269503/c653986a-8a53-4c93-858a-569cf4631d94)
> 
> [android-files.zip](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/11495226/android-files.zip)
> 

Where is the box of NekoBox icon?

**Comment by xmha97** [comment]
@Misaka-blog If I design a good monochrome icon, will you use it?

**Comment by normiridium** [comment]
https://nekodex.org/brand :3
