### ISSUE TITLE
[Feature Request] 耗电优化

### ISSUE THREAD

**Issue by npwc** [MatsuriDayo/NekoBoxForAndroid#142]
**描述建议**

用的是NaïveProxy模式（不确定是否有关系），和SagerNet相比，NekoBox耗电高。

同样的设备和配置，使用12小时，SagerNet耗电**1%**，NekoBox耗电**12%**。

**建议的必要性**

延长电池寿命

**Comment by btaskel** [comment]
确实比较高……
