### ISSUE TITLE
是否可以增加mkcp支持

### ISSUE THREAD

**Issue by wangp-blog** [MatsuriDayo/NekoBoxForAndroid#159]
**描述建议**
当前NB4A未支持mkcp相关的协议，建议增加mkcp支持。
当前直接导入mkcp相关的协议节点时，点击测试出现“失败，连接重置”。
**建议的必要性**
作为一个客户端，应该允许用户使用这个协议，即使它并不安全。

**Comment by aetoray** [comment]
https://sing-box.sagernet.org/zh/configuration/shared/v2ray-transport
