### ISSUE TITLE
能否增加使用本地 SIP003 插件功能

### ISSUE THREAD

**Issue by tdjnodj** [MatsuriDayo/NekoBoxForAndroid#16]
**描述建议**

像 shadowsocks-Android、SagerNet、Matsuri 那样支持选择已有的 shadowsocks-plugin

![](https://raw.githubusercontent.com/tdjnodj/picture_bed/main/issue/2023031901.jpg)

**建议的必要性**

丰富 shadowsocks 功能

**Comment by jhli999** [comment]
你的v2ray-plugin能正常使用吗，你这个好像不是nekobox装这么多插件，我这个插件的ss用不了，换了几家的节点都不能使用
