### ISSUE TITLE
当所处的分组开启 selector 时，调整设置后，“应用”按钮不生效

### ISSUE THREAD

**Issue by ghost** [MatsuriDayo/NekoBoxForAndroid#180]
**描述问题**

预期行为：在调整 FakeDNS 后点击 “应用” 按钮以加载配置。

实际行为：点击 “应用” 后并没有作用

**如何复现**

好像不只 FakeDNS 有这个问题，其他设置也有，只是不好观察。

经测试，该 bug 仅在开启 `selector` 的情况下存在。

关闭 FakeDNS，随机查询一个以 google.com 结尾的域名（如 diidnf.google.com），根据分流规则，这个域名将使用远程 DNS 解析。

随后开启 FakeDNS 并点击 “应用”，再次查询这个域名的 DNS，还是无结果。

手动重启配置，再次查询，返回假 IP。

**日志**

请在邮箱查看

**Comment by jaoyina** [comment]
搭车问下group 设置里的use selector是干什么用的？

**Comment by jaoyina** [comment]
> 

就是切换不会断开原来的意思吗？
