### ISSUE TITLE
当设置“IPV6路由”选项为禁用时，无法连接单ipv6公网的vmess服务器。

### ISSUE THREAD

**Issue by dev-techmoe** [MatsuriDayo/NekoBoxForAndroid#213]
**描述问题**

预期行为：

首先我很喜欢singbox还有nekobox。

我为了连回家里的内网资源，网关上搭了一个vmess服务器。

国内ISP不给公网IPV4，导致我只能走v6连回来。

我的国外梯子没配置ipv6，这个ipv6路由我也一直是关着的。

按照我的理解这个应该只影响传入nekobox的连接的ipv6路由行为，而不应该影响传出到vmess服务器时的ipv6行为。

实际行为：

关了ipv6路由，我就连不回去家里单ipv6公网vmess的服务器，打开后一切正常。

**如何复现**

如上所述。

**日志**

半夜了，累了，如果需要日志的话明天起来我处理。

**Comment by dev-techmoe** [comment]
问题应该出在DNS解析上。服务器地址直接填ipv6地址没问题，填域名就连不上。

禁用ipv6时，似乎日志也有解析失败的提示。

**Comment by dev-techmoe** [comment]
> 方法3 的意思是你自己做2的处理（下载最新版，点击配置编辑界面的右上角菜单）
> 
> `{"domain_strategy":"prefer_ipv6"}`

下载1.1.5版本，按照如上配置之后工作正常。

感谢您的耐心指导。

**Comment by its0ka** [comment]
@arm64v8a did i understood correctly that nekobox for android will never be able to connect to only ipv6 AAAA domains by default?

**Comment by dev-techmoe** [comment]
> @arm64v8a did i understood correctly that nekobox for android will never be able to connect to only ipv6 AAAA domains by default?

No, just download the latest version

And set "Custom outbound JSON" (sry idk what is this translated in English) to 

```
{"domain_strategy":"prefer_ipv6"}
```

for your outbound, all works prefectly

**Comment by its0ka** [comment]
@dev-techmoe what i meant is that "Domain strategy for Server address" in settings works like this for me:
auto - error
prefer_ipv6 - OK
prefer_ipv4 - OK
ipv4_only - error
ipv6_only - OK
and i don't understand why it errors on auto.
my domain only has AAAA dns record.

you can test it even if you don't have an ipv6 capable ISP or server by converting your ipv4 address to ipv6 (https://iplocation.io/ipv4-to-ipv6) and making only an AAAA dns record with it

**Comment by its0ka** [comment]
@arm64v8a auto = ipv4_only?

**Comment by dev-techmoe** [comment]
> @arm64v8a auto = ipv4_only?

I think it will depend on what your DNS server response.

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/c9ef22fe3406c8c9aad2efaabbb9ede5f22d866c/app/src/main/java/moe/matsuri/nb4a/SingBoxOptionsUtil.kt#L9

https://github.com/SagerNet/sing-box/blob/ef0c3ec13dc659bb480e42c9e6ff3eb83c3b2bae/experimental/libbox/dns.go#L117
