### ISSUE TITLE
No connection after updating to 1.1.7

### ISSUE THREAD

**Issue by HosseinShahverdi** [MatsuriDayo/NekoBoxForAndroid#241]
**描述问题**
No connection in the new version (1.1.7)
预期行为：
Dear developers, prior to the stating of the problem, i want to thank you for your efforts 
实际行为：
The problem I'm getting is that after updating to the latest version although i get pings for config i can not connect to the Internet. My android version is 13
**如何复现**

提供有帮助的截图，录像，文字说明，订阅链接等。

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by hesam13733** [comment]
hello
I had same problem 
install 1.1.5 version and and go to settings check "use system DNS as Direct DNS" I hope that solve the problem

**Comment by BK8000L** [comment]
in 1.1.7 fill "local" in the Direct DNS
