### ISSUE TITLE
仪表板web显示错误

### ISSUE THREAD

**Issue by 1271446615** [MatsuriDayo/NekoBoxForAndroid#269]
在自定义路由规则之后，打开webUI，就会出现这样的情况，字体全部重合在一起了，无论是用浏览器还在APP自带的打开都这样
![Screenshot_2023-08-08-15-11-27-309_com microsoft emmx](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/118651968/62cc42a3-6f82-4960-9326-ea4e2d52ea06)
![Screenshot_2023-08-08-15-15-47-756_moe nb4a](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/118651968/36638b3b-b295-4bae-8413-e127b68d0c9a)

**Comment by 1271446615** [comment]
![Screenshot_2023-08-08-16-16-29-315_com microsoft emmx](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/118651968/b59cddbe-bdc5-420f-bdad-b46ec3ff631d)
还是一样的字体重叠

**Comment by 1271446615** [comment]
> http://yacd.metacubex.one/
> 
> 打开看这个网站是否有同样问题

![Screenshot_2023-08-08-16-16-29-315_com microsoft emmx](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/118651968/34486b3a-7452-4850-90c0-8b02b1d50a67)
还是一样的字体重叠

**Comment by Misaka-blog** [comment]
那就是上游问题，没辙
