### ISSUE TITLE
how to Project compilation process in windows

### ISSUE THREAD

**Issue by ca3tiel** [MatsuriDayo/NekoBoxForAndroid#276]
hi
i want to Build your project locally and im windows user
but i get some error you can see in this screenshot
![Screenshot 2023-08-11 150712](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/57295411/a689c59d-f7c4-47cb-b3c5-6ef08fc09c4f)

i try using you instructions [#177](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/177) and [#162](https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/162) but its not work for windows users

please send a full instruction for windows users

thanks

**Comment by ca3tiel** [comment]
hi
I using git bash and at first step I was run the fallowing code:

```
./run lib core
```
and get this error:
```
>> buildScript/lib/core.sh
Error: NDK not found.
Error: NDK not found.
```

then I use this:
```
export ANDROID_NDK_HOME=/d/Android/Sdk/ndk/25.0.8775105
```
and `./run lib core` work but get gomobile error like this screenshot:

![Screenshot 2023-08-11 231052](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/57295411/cb572fac-3d3d-4bbc-beaf-378614c968f9)

so I try to install gomobile by 
```
go install golang.org/x/mobile/cmd/gomobile@latest
```
I'm getting this error :

![Screenshot 2023-08-11 231813](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/57295411/3f811f60-bcba-4ed5-b122-bb24d91d89b2)

any help would be appreciated

**Comment by janahnovin** [comment]
Installing through git bash, I get an error and can't install, please help me

itrooz@DESKTOP-UVQ5S47 MINGW64 ~/Desktop/NekoBoxForAndroid-1.2.0 (master)
$ ./run lib core                                                         
>> buildScript/lib/core.sh
Error: NDK not found.
Error: NDK not found.

itrooz@DESKTOP-UVQ5S47 MINGW64 ~/Desktop/NekoBoxForAndroid-1.2.0 (master)
$ export ANDROID_NDK_HOME=/d/Android/Sdk/ndk/25.0.8775105                

itrooz@DESKTOP-UVQ5S47 MINGW64 ~/Desktop/NekoBoxForAndroid-1.2.0 (master)
$ go install golang.org/x/mobile/cmd/gomobile@latest
bash: go: command not found

**Comment by janahnovin** [comment]
Please, when the source of a project is uploaded, put the complete project file. I don't think anyone has been able to extract the output from the source, there is a libcore error.

**Comment by janahnovin** [comment]
Is it possible to give more guidance?Many people have this problem, it should be solved once and for all, thank you

**Comment by xchacha20-ietf-poly1305** [comment]
> 没自己发现的人可能无法作出有效贡献
