### ISSUE TITLE
Nekobox closes in bakckground.

### ISSUE THREAD

**Issue by smsalehi** [MatsuriDayo/NekoBoxForAndroid#280]
After a period of inactivity on my Android phone (screen off), Nekobox automatically closes. I have disabled battery optimization, but the issue persists. Nekobox is the only app exhibiting this behavior, as other proxy apps such as v2rayng, matsuri, and v2fly do not have this issue. Additionally, when this issue occurs, the notification for the Nekobox app remains visible in the Android notification panel. Here is the logcat for reference:

08-15 13:02:07.747  1655  1822 W ProcessStats: Tracking association SourceState{f2550d0 system/1000 BTopFgs #250763} whose proc state 2 is better than process ProcessState{1e5ba8e moe.nb4a:bg/10541 pkg=moe.nb4a} proc state 3 (427 skipped)
08-15 13:06:13.069 15108 15132 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15132 (Thread-6), pid 15108 (moe.nb4a:bg)
08-15 13:06:18.261  4985  4985 F DEBUG   : Cmdline: moe.nb4a:bg
08-15 13:06:18.261  4985  4985 F DEBUG   : pid: 15108, tid: 15132, name: Thread-6  >>> moe.nb4a:bg <<<
08-15 13:06:18.262  4985  4985 F DEBUG   :       #00 pc 000000000040d0b8  /data/app/~~k6yvmHGfw9Yab0Zsa2S6rA==/moe.nb4a-4w_-0fQ-rNodOKZzKxuqSQ==/lib/arm64/libgojni.so
08-15 13:06:18.369  1655  1819 W ActivityManager: Exception when unbinding service moe.nb4a/io.nekohasekai.sagernet.bg.VpnService
08-15 13:06:18.411  1655  5900 I ActivityManager: Process moe.nb4a:bg (pid 15108) has died: prcp FGS

**Comment by smsalehi** [comment]
Furthermore, it is important to note that this issue occurs in both version 1.1.8 and version 1.2, which are the latest versions of the Nekobox app.

**Comment by zhfiann** [comment]
我也有此问题，1.20版本。以前的版本也有此问题。clash也是同样的问题。surfboard无此问题。

**Comment by zhfiann** [comment]
我用的是小米手机，也是这个问题，在后台一段时间后想启动代理整个界面没有任何反应。以前clash也是同样的问题。不知道使用其它手机的有没有类似问题？

**Comment by fgghghddf** [comment]
me too ，realme  phone

**Comment by fgghghddf** [comment]
Yes, the new version is caused by this kind of problem. I changed it to version 1.1.6 and it didn’t appear

**Comment by fgghghddf** [comment]
Yes, this problem exists in the new version, I changed it to version 1.1.6 and it did not appear

**Comment by smsalehi** [comment]
I have currently installed version 1.1.2, and I can confirm that it is working properly.
 This issue is very critical, as it puts the identity of users at risk.
 The entire use of the VPN is now in question.
 I am wondering if this issue still exists after several updates.

**Comment by smsalehi** [comment]
I have currently installed version 1.1.2, and I can confirm that it is working properly.
 This issue is very critical, as it puts the identity of users at risk.
 The entire use of the VPN is now in question.
 I am wondering if this issue still exists after several updates.

**Comment by EvilGremlin** [comment]
Still exist and looks like it's a problem with older android versions (shuts down in 10, stays on in 12)

**Comment by KweezyCode** [comment]
same issue, could it be fixed instead of closing as not planned?
