### ISSUE TITLE
启用Clash API的作用是什么？

### ISSUE THREAD

**Issue by photkey** [MatsuriDayo/NekoBoxForAndroid#290]
我想通过API切换节点，启用Clash API好像是没效果啊，127.0.0.1:9090可以访问，但是获取不到节点，难道这个是还需要安装Clash，这个就只是控制Clash的吗？

**Comment by xchacha20-ietf-poly1305** [comment]
解压 [Yacd-meta](https://github.com/MetaCubeX/Yacd-meta) （或其他面板）到 `nekoray/dashboard` 目录中，然后访问 <http://127.0.0.1:9090/ui>
