### ISSUE TITLE
androidtv  version

### ISSUE THREAD

**Issue by rezakhalilianadel1380** [MatsuriDayo/NekoBoxForAndroid#293]
hello , thank you for this incredible app , it would be great if you released adnorid tv verison of nekobox  thank you   again for your app

**Comment by Dr4tez** [comment]
I use NekoBox on an Android device with remote control. I have to turn on the air mouse for the NekoBox interface, which is not very convenient. A version for Android TV would be very useful.

**Comment by Misaka-blog** [comment]
Not planned, thx
