### ISSUE TITLE
是否考虑增设hosts功能

### ISSUE THREAD

**Issue by inanb** [MatsuriDayo/NekoBoxForAndroid#297]
**描述建议**
增设hosts功能，使得域名可以对应静态IP

**建议的必要性**
非root手机可以方便使用hosts功能，如果使用virtual-hosts，没有方法和vpn同时使用...

**Comment by xchacha20-ietf-poly1305** [comment]
可以找 sing-box 要

**Comment by Xuchengen** [comment]
我觉得还是有必要增设hosts功能。

举个例子，安卓手机FCM推送直连才能稳定接收消息推送，但是谷歌家FCM IP众多通过域名解析获取的部分IP有可能是被屏蔽或污染的IP。通过手动指定hosts可以规避该问题。

我注意到nokobox可以自定义配置json，但能不能实现自定义dns模块间接实现指定hosts功能我不是很清楚，希望有大佬能给出一个参考。
