### ISSUE TITLE
RELEASE (tag)1.2.3 所指的commit为什么更新了?

### ISSUE THREAD

**Issue by ddzzkunye** [MatsuriDayo/NekoBoxForAndroid#310]
RELEASE (tag)1.2.3 所指的commit为什么更新了?  
RT, 原来指向的是a7bf95b374dd9448f63887184cd426d4e48c9850,  
现在指向了334cdb0c6d4c8d7fa8f1cf42b402e27eefff85bc.

**Comment by imldy** [comment]
旧的1.2.3指向的commit错误的调小了VERSION_CODE，而非增大。

**Comment by ddzzkunye** [comment]
感谢
