### ISSUE TITLE
BUG: 支持自定义证书

### ISSUE THREAD

**Issue by mmm8955405** [MatsuriDayo/NekoBoxForAndroid#322]
自定义证书配置太麻烦了
https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/167

**Comment by mmm8955405** [comment]
https://github.com/MatsuriDayo/NekoBoxForAndroid/actions/runs/5161379652

使用方法：

把 Mozilla 或任何 ca.pem 文件，放到 /sdcard/Android/data/moe.nb4a/files/ca.pem
重启，程序启动时将自动加载这个文件中的证书（替换system证书）
开启 loglevel ，在日志中可查看是否加载成功

**Comment by mmm8955405** [comment]
未必有sd卡这个目录/sdcard/Android/data/moe.nb4a/files/ca.pem

**Comment by mmm8955405** [comment]
> 根据安卓机制，若没有SD卡，且在单用户情况下，`/sdcard`路径将被链接至`/storage/emulated/0`，此目录为公共外部存储，即一般文件管理器所显示的“手机存储”/“内部存储”。
> 
> 所以在文件管理器中寻找`Android/data/moe.nb4a/files/`目录即可。
> 
> 参考文章：https://www.jianshu.com/p/4fd23c4a1173

我看了一台小米手机， 自带的软件都找不到/storage/emulated/0这个目录

**Comment by mmm8955405** [comment]
今天最新测试。即使配置了自签ca证书在对应目录之后，测试可以连接，但是无法正常使用

**Comment by imldy** [comment]
> 今天最新测试。即使配置了自签ca证书在对应目录之后，测试可以连接，但是无法正常使用

建议贴出日志或者截图。

“可以连接”、“无法正常使用”指什么？

**Comment by mmm8955405** [comment]
![ss](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/d10b8ce7-8720-4e9b-9496-0d68c4a9b623)
![ss2](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/aa5600a6-714b-4e8e-964b-860a4eb6e21f)
![ss3](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/c16e61c7-2ca8-4ad6-acf9-29d2a3cb4b11)

**Comment by mmm8955405** [comment]
就是测试连接提升成功， 但是还是无法正常使用代理。
这些版本都试过了
![ss4](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/c8b385aa-f49f-4348-a874-c4171e6ee236)

**Comment by mmm8955405** [comment]
这是配置，
![ss5](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/f80629e4-1ddf-4dbc-99f0-4e926de85ba0)

hysteria的windows端，可以正常试用，同样的服务器配置自定义CA

**Comment by imldy** [comment]
#167 说的是订阅链接的证书，不是节点的证书。

我没用过hysteria节点，不过看起来，你或许可以试试把你的证书 填 `证书(链)` 这里：

![image](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/53949747/27754818-332c-4f16-a797-440cfa00498f)

**Comment by mmm8955405** [comment]
> #167 说的是订阅链接的证书，不是节点的证书。
> 
> 我没用过hysteria节点，不过看起来，你或许可以试试把你的证书 填 `证书(链)` 这里：
> 
> ![image](https://user-images.githubusercontent.com/53949747/266287036-27754818-332c-4f16-a797-440cfa00498f.png)

这个证书（链）是什么意思，应该填入什么？
 是填写证书的路径像这样：Android/data/moe.nb4a/files/ca.pem?
还是说把证书放在一个可以访问的url下？ http://test/my/ca.pem?

**Comment by imldy** [comment]
根据程序代码判断，应该是填证书文件里面的所有字符。

应该就是你这里 https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/322#issuecomment-1708329289 的证书，复制其中所有内容粘贴。

至于“证书链”，请自行搜索相关含义。不过这里界面显示的确实有歧义。


相关代码：

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/fea54375d36c870d8c92bb981082d24e26261685/app/src/main/res/values-zh-rCN/strings.xml#L237

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/fea54375d36c870d8c92bb981082d24e26261685/app/src/main/res/xml/hysteria_preferences.xml#L68

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/fea54375d36c870d8c92bb981082d24e26261685/app/src/main/java/io/nekohasekai/sagernet/ui/profile/HysteriaSettingsActivity.kt#L30

https://github.com/MatsuriDayo/NekoBoxForAndroid/blob/fea54375d36c870d8c92bb981082d24e26261685/app/src/main/java/io/nekohasekai/sagernet/fmt/hysteria/HysteriaFmt.kt#L315

SingBox文档：https://sing-box.sagernet.org/configuration/shared/tls/#certificate

**Comment by mmm8955405** [comment]
![11](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/01106270-4dfe-401f-8669-b81e1cbb0b00)
![22](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/7c5f2242-ae44-4c77-975d-96b0633fa437)

填入“证书”之后的效果。版本是最新的1.2.3

**Comment by mmm8955405** [comment]
这是hysteria服务端的配置
![333](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/5687907/fe82512a-3f81-402c-a1fe-d376defd4542)

**Comment by mmm8955405** [comment]
> 填入“证书”之后的效果。版本是最新的1.2.3
很奇怪，多试几次之后可以了，我应该把这个bug关了

**Comment by mmm8955405** [comment]
<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/890adbc7-a8e0-4d06-bca2-a612db1a1294" />

我要重新打开这个问题, 可能是singbox的问题， 填写证书链之后， 版本1.29一直到最新版本都会有这个错误
