### ISSUE TITLE
建议：针对每个节点可以有单独的多路复用选项

### ISSUE THREAD

**Issue by yzx23333** [MatsuriDayo/NekoBoxForAndroid#328]
## 描述建议
因为singbox有自己实现的一套不错的多路复用，不过必须配合singbox服务端使用……大部分其他的同协议不同后端不支持便会无法连接
想要区分开支持和不支持的节点以单独设置
## 建议的必要性
功能请求优先级不高，只是想先提出建议

**Comment by a-bcdef** [comment]
中国域名规则  绕过  打开， Tiktok连不上网怎么解决？谢谢大神。
