### ISSUE TITLE
支持 mieru 插件

### ISSUE THREAD

**Issue by enfein** [MatsuriDayo/NekoBoxForAndroid#359]
## 描述建议

mieru 曾经在 SagerNet 上推出过插件。如今 SagerNet 项目几乎停止更新，我们希望可以在 NekoBox 上支持 mieru 插件，以便让先前的用户迁移过来。我作为 mieru 项目的作者，可以帮助编写和长期维护 mieru 插件。

## 建议的必要性

向原先 SagerNet mieru 插件的用户继续提供支持，例如这个请求 https://github.com/enfein/mieru/issues/84.

**Comment by ellahmezar** [comment]
@arm64v8a 
Nekobox should support Meiro Directly like TUIC and other configs  😍

**Comment by yjd** [comment]
@enfein 题外话，mieru支持cf中转吗？

**Comment by enfein** [comment]
@yjd 需要 https://github.com/enfein/mieru/issues/77 才能支持 cloudflare warp

**Comment by Misaka-blog** [comment]
@enfein 可以支持，pr welcome

**Comment by Misaka-blog** [comment]
另外，我们的插件仓库在：https://github.com/MatsuriDayo/plugins
