### ISSUE TITLE
BUG: neko无法连接转发后的节点

### ISSUE THREAD

**Issue by kalakalalalala** [MatsuriDayo/NekoBoxForAndroid#375]
## 描述问题
一台小鸡使用流量转发之后：先将xui面板里的节点导入nekobox，再根据xui设置的端口ip进行转发。将nekobox中的ip和端口改成转发提供的。无法连接
预期行为：

实际行为：

## 如何复现
一台小鸡使用流量转发之后：先将xui面板里的节点导入nekobox，再根据xui设置的端口ip进行转发。将nekobox中的ip和端口改成转发提供的。
![photo_2023-10-22_12-24-08](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/136727803/e61dfce7-a2ba-47ea-b66a-ba914bc8b319)

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。
[NB4A 5092319345398171288.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13062365/NB4A.5092319345398171288.log)

**Comment by purofle** [comment]
请问选用的是什么协议？

**Comment by ZYGLQexplorer** [comment]
Your password base64 length is incorrect. If this was generated by some software, please give them feedback.

**Comment by kalakalalalala** [comment]
你好，nekobox的开发者。我在xui面板上用的shadowsocks协议

explorer ***@***.***> 于 2023年11月7日周二 20:40写道：

**Comment by ZYGLQexplorer** [comment]
密码不对
