### ISSUE TITLE
BUG: 手动添加socks服务器不可以填写密码

### ISSUE THREAD

**Issue by cjl88615** [MatsuriDayo/NekoBoxForAndroid#376]
## 描述问题
手动添加socks服务器的话，不出现密码输入框，只出现用户名输入框，这个问题从1.2.4版本就开始出现了，到现在一直未修复。

**Comment by cjl88615** [comment]
![Screenshot_20231023_114536.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/70687520/8a5549ea-e055-474e-9e2f-86548b5ac708)

**Comment by cjl88615** [comment]
如上图所示，没有出现填写密码的框框，只出现了填写用户名的框框

**Comment by Misaka-blog** [comment]
> 如上图所示，没有出现填写密码的框框，只出现了填写用户名的框框

已成功复现，你可以重新选择一下协议版本，然后再次选择 socks5 就可以填写密码了

**Comment by cjl88615** [comment]
这样确实可以，但是在1.2.3版本前都是正常的，从1.2.4版本开始这个密码输入框才被隐藏掉，能否给改回来啊？还是原来那样比较方便啊

**Comment by purofle** [comment]
> 这样确实可以，但是在1.2.3版本前都是正常的，从1.2.4版本开始这个密码输入框才被隐藏掉，能否给改回来啊？还是原来那样比较方便啊

将在新版本中修复。
