### ISSUE TITLE
1.2.4以后的版本，选中的代理APP，国内、国外分流问题

### ISSUE THREAD

**Issue by Qpasser-by** [MatsuriDayo/NekoBoxForAndroid#380]
在1.2.4以后所有的版本，经过测试，发现如果把chrome加入代理的APP中，然后在路由里面开启绕过中国域名 中国IP规则，实际上访问CN的域名或者IP，还是会经过代理到国外节点再访问，而不是直接链接访问这些网站或者服务，ip138等一些列显示IP的地址的网站所显示的IP均为vps或者机场节点IP，不单单是chrome ，尝试把微信 支付宝 等一些国内APP加入代理列表然后一样会这样，降级安装到1.2.4版本就不会有这种问题，chrome访问国内一些IP网站显示为国内IP地址，国外IP网站，显示为机场节点IP。
         无意中发现最近VPS用的很多流量，才发现这个问题，从1.2.7一路降级安装到1.2.4才解决，中间所有配置选项信息都没改变，就降级安装后再打开连接节点测试，最终到1.2.4后不再复现这个问题。
      两部不同品牌手机，系统都为Android 13版本 ，一部chromeOS平板，尝试用公司企业宽带，家庭宽带 电信 联通移动网路，表现全部一致。
![image](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/118433595/2efff2df-d0ea-400c-9a0d-c3d4e212bf7c)

**Comment by Misaka-blog** [comment]
请提供下应用日志
