### ISSUE TITLE
BUG: workflows编译不过

### ISSUE THREAD

**Issue by Mronezc** [MatsuriDayo/NekoBoxForAndroid#381]
@Misaka-blog 同步了一下真机编译报错如下
actions也是这个错，编译了一下你更改前的旧版本都没任何问题
`Resolving deltas: 100% (90/90), done.`
`/e/test/sing-quic /e/test /e/test/sing-box-extra`
`fatal: reference is not a tree: c1dc95ed1e63b8b30160f59831f55990c7660d75`
`write E:\test\NekoBoxForAndroid-main\libcore\.build\src\go.mod`
`go: error reading go.mod: missing module declaration. To specify the module path:`
        `go mod edit -module=example.com/mod`
`C:\Users\Administrator\go\bin\gomobile.exe: go mod tidy -v failed: exit status 1`

**Comment by Misaka-blog** [comment]
实机的环境是 Windows 是吧，记得 clone 下这个组织的 sing-quic、sing-box 和 sing-box-extra

**Comment by Mronezc** [comment]
> 实机的环境是Windows是吧，记得克隆下这个组织的sing-quic、sing-box 和 sing-box-extra

是windows环境执行./run lib core以后就clone有sing-quic、sing-box 和 sing-box-extra这三个了，我重新克隆这个项目改了一下workflows只编译aar都不行，但是在你两次提交之前的版本actions和真机都能编译

**Comment by Mronezc** [comment]
> 实机的环境是Windows是吧，记得克隆下这个组织的sing-quic、sing-box 和 sing-box-extra

是windows环境执行./run lib core以后就clone有sing-quic、sing-box和sing-box-extra这三个了，我重新克隆这个项目改了一下工作流程只编译aar都不行，在但是你两次提交之前的版本操作和真机编译

**Comment by Misaka-blog** [comment]
> > 实机的环境是Windows是吧，记得克隆下这个组织的sing-quic、sing-box 和 sing-box-extra
> 
> 是windows环境执行./run lib core以后就clone有sing-quic、sing-box和sing-box-extra这三个了，我重新克隆这个项目改了一下工作流程只编译aar都不行，但是在你两次提交之前的版本操作和真机都能编译

现在应该是可以了，重新克隆一下项目

**Comment by Mronezc** [comment]
> > > 实机的环境是Windows是吧，记得克隆下这个组织的sing-quic、sing-box 和 sing-box-extra
> > 
> > 
> > 是windows环境执行./run lib core以后就clone有sing-quic、sing-box和sing-box-extra这三个了，我重新克隆了这个项目改了一下工作流程只编译aar都不行，但是在你在版本操作和真机编译之前进行两次提交
> 
> 现在应该可以了，重新克隆一下项目

OK了试了一下编译都没问题了
