### ISSUE TITLE
对Hysteria2的端口跳跃功能支持不完善

### ISSUE THREAD

**Issue by sangyufeiwanya** [MatsuriDayo/NekoBoxForAndroid#383]
## 描述建议
版本1.2.7
在Hysteria2的协议配置窗口设置端口范围并打开连接后，不能像Hysteria1一样识别端口跳跃。
从日志分析端口设置为10000-19999时，生成配置中无端口一项，将默认连接服务端端口0。
## 建议的必要性
墙内对封端口很积极，望早日支持。

**Comment by Misaka-blog** [comment]
已经做好，可以在 Actions 下载测试版本的 apk 安装包文件

**Comment by Misaka-blog** [comment]
正式版将于稍后的一段时间会发布
