### ISSUE TITLE
BUG: Crash detected , and some problems in log file 

### ISSUE THREAD

**Issue by ellahmezar** [MatsuriDayo/NekoBoxForAndroid#384]
Hi my dear friends @arm64v8a @Misaka-blog 
Hope you're doing great 🤍🌱
Connection in Nekobox stops several time , so I uploaded the log file for you to inspect the error , and fix it .
Wish you the best .
Sincerely Yours .

[NB4A 4238557069247198539.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13170727/NB4A.4238557069247198539.log)

**Comment by Misaka-blog** [comment]
I think it maybe fixed, you can download test version of apk from Actions runs: https://github.com/MatsuriDayo/NekoBoxForAndroid/actions/runs/6649169719

**Comment by ellahmezar** [comment]
Hi , @Misaka-blog 
Unfortunately the problem still exists .

**Comment by Misaka-blog** [comment]
> Hi , @Misaka-blog Unfortunately the problem still exists .

Check out https://github.com/MatsuriDayo/NekoBoxForAndroid/actions/runs/6653131461

**Comment by ellahmezar** [comment]
Hi @Misaka-blog @arm64v8a  .
The problem still exists in Version 1.2.8 .
[NB4A 6043719130740634898.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13200866/NB4A.6043719130740634898.log)
