### ISSUE TITLE
userpass 验证模式无法通过

### ISSUE THREAD

**Issue by liuxyon** [MatsuriDayo/NekoBoxForAndroid#396]
我尝试密码框填入 A: 12554df5ewe 或A:12554df5ewe 都是无法工作.

如果服务器使用 userpass 验证，格式必须是 username:password

auth:
  type: password
  password: your_password 
  userpass: 
    user1: pass1
    user2: pass2
    user3: pass3

**Comment by Misaka-blog** [comment]
请提供完整日志

**Comment by Hiradpi** [comment]
hello im having the same problem when i set my server config to userpass 
```
auth:
  type: userpass  
  userpass:
    user1: mypassword
```

and provide the password in the format user1:mypassword authorization fails due to invalid hash 

i underestand that this problem is from sing-box but since you modified the core before please consider fixing this too <3
