### ISSUE TITLE
BUG: 分应用代理情况下，谷歌系服务间隙性断网

### ISSUE THREAD

**Issue by 17yuite** [MatsuriDayo/NekoBoxForAndroid#397]
## 描述问题

预期行为：分应用代理情况下，谷歌系服务间隙性断网

实际行为：分应用代理情况下，谷歌系服务间隙性断网

## 如何复现
本地环境：三星国行系统，wifi或者移动数据（都会有一样的问题），neko应用是最新的版本
nekoray安卓版，选择分应用代理，在搜索栏输入关键词“google”，并将搜索出来的服务进行勾选代理。
注意，我这里是说间隙性断网，并且其他应用能正常被代理，如推特。
（我说一下出现这种问题我是如何解决的：关闭分应用代理，则一切正常）
------
我查阅相关资料，发现也有人与我有一样的问题。而且这个问题不光出现在neko里面，v2rayng也会有一样的问题，下贴其他人的issue：
https://github.com/Kr328/ClashForAndroid/issues/113
https://github.com/gfwlist/gfwlist/issues/1009

------
不求能有大的解决，希望能在分应用代理里面将那个需要代理的服务标识出来，或者能有其他更好的解决方法。
多谢。

**Comment by jaoyina** [comment]
断网是指整个系统都不能上网？我也是三星国行，2台设备都没问题。

**Comment by 17yuite** [comment]
> 断网是指整个系统都不能上网？我也是三星国行，2台设备都没问题。

不是整个系统断网，是谷歌系服务不能访问网络，就算开了代理。
还有，你是分应用代理吗？如果是，在分应用代理情况下，试试清空谷歌play数据和缓存，然后重新进入看看

**Comment by 17yuite** [comment]
我在此说一下我都问题复现方式：
前提先将谷歌系服务数据清空（如，清空google play数据和缓存即可，）
neko或者v2rayng，在分应用代理情况下，打开谷歌系服务(如，youtube，google play或者youtube music)。
然后就会发现，应用无法被代理，但打开其他非谷歌系应用，一切正常。
注意，我这个问题有个前提，间隙性，之前经常遇到，一度因此关闭分应用代理

**Comment by 17yuite** [comment]
问题不是很迫切，就此关闭吧，能用就行

**Comment by CussiusKon** [comment]
我的play商店直接下不动，以前在suger、v2raynG都遇到过。倒是在clash android上面一直都没问题。很奇怪，应该是分流问题吧

**Comment by 17yuite** [comment]
用黑名单模式，将国内应用通通绕过。或者白名单模式，将设置和系统这两个服务代理就行。我现在已经正常了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 17yuite** [comment]
你可能没有将下载那个服务进行代理，建议用黑名单模式吧，这样不容易出问题

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Chinawenzi** [comment]
使用白名单模式，勾选如下服务即可
![Uploading Screenshot_2024-01-25-10-41-47-926_moe.nb4a.jpg…]()

**Comment by Chinawenzi** [comment]
白名单勾选，谷歌服务 ，谷歌商店，谷歌服务框架这三个，其他谷歌服务不需要勾选
