### ISSUE TITLE
libcore.aar

### ISSUE THREAD

**Issue by AliZamani-Developer** [MatsuriDayo/NekoBoxForAndroid#401]
![Untitled](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/37456931/43966f8c-5d18-4ebd-aebc-e47a264c7eb4)
![Untitled2](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/37456931/7f056a7d-4311-4939-a011-1704778a80cc)

I want to compile libcore but I get this error. Thank you for your help

**Comment by m1faridi** [comment]
به پوشه lib اضاقه کن 
<img width="353" alt="Screenshot 2023-11-01 at 22 23 09" src="https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/7335680/dd02ef7c-3a57-43ac-8b66-0ba95767bc50">

**Comment by AliZamani-Developer** [comment]
> به پوشه lib اضاقه کن <img alt="Screenshot 2023-11-01 at 22 23 09" width="353" src="https://user-images.githubusercontent.com/7335680/279772273-dd02ef7c-3a57-43ac-8b66-0ba95767bc50.png">

دقیقا همین فایل نیاز دارم میشه لینکشو بدی

**Comment by m1faridi** [comment]
https://filetransfer.io/data-package/OX3sGJT9#link

**Comment by AliZamani-Developer** [comment]
> https://filetransfer.io/data-package/OX3sGJT9#link

دلیل این خطایی که هنگام کامپایل برام داده چیه می دونید ؟

**Comment by m1faridi** [comment]
من با ubuntu 20 خروجی گرفتم

**Comment by MingtimeThis** [comment]
@AliZamani-Developer 楼上的解决了吗

**Comment by Mrkoopaei** [comment]
@AliZamani-Developer Would you please renew the download link?
thanks

**Comment by Mrkoopaei** [comment]
@m1faridi Would you please renew the download link?

thanks
