### ISSUE TITLE
Feature Request: Add new V2Ray transport : "HTTPUpgrade"

### ISSUE THREAD

**Issue by ellahmezar** [MatsuriDayo/NekoBoxForAndroid#403]
Hi my friends @purofle @arm64v8a @Misaka-blog 
Hope you're doing great .
Please add this new V2Ray transport called "HTTPUpgrade" to Nekobox as soon as possible .
Many thanks for your efforts .
Wish you the best .

**Comment by Misaka-blog** [comment]
Already added, will release for next version
