### ISSUE TITLE
SSH - ADD FEATURES FOR SSH + PAYLOAD + PROXY AND SSH + PAYLOAD + PROXY + SSL

### ISSUE THREAD

**Issue by MelisaTanaga** [MatsuriDayo/NekoBoxForAndroid#413]
I hope there are new features added to SSH here, there are lots of free SSH accounts compared to Vmess, 
ssh + payload + proxy 
ssh + payload + proxy + ssl 
ssh + enhanced + payload + proxy 
ssh + enhanced + payload + proxy + ssl

**Comment by purofle** [comment]
Please create issue on https://github.com/SagerNet/sing-box/issues
