### ISSUE TITLE
安卓12无法安装

### ISSUE THREAD

**Issue by WFJ1987** [MatsuriDayo/NekoBoxForAndroid#415]
![photo_2023-11-08_11-17-40](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/129924492/1b1fc83a-8bce-4f6e-982c-0c43852a0b4f)
## Describe the problem

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by purofle** [comment]
使用的是什么手机？什么系统？

**Comment by WFJ1987** [comment]
> 使用的是什么手机？什么系统？

可以了，我装错版本了。
