### ISSUE TITLE
BUG: 失败，链接被重置

### ISSUE THREAD

**Issue by lyx32** [MatsuriDayo/NekoBoxForAndroid#421]
## Describe the problem

Expected behavior: 正常连接

Actual behavior:不能连接

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.
![连接被重置](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/7733528/da552cb9-5b98-41b8-913c-c7344b92193a)

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.
[log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13317396/NB4A.1152243458918008738.log)

**Comment by lyx32** [comment]
装好之后，第一次可以用。关了等一会在打开就这样。
然后我不知道怎么点的，然后又可以了。
现在又不行了。

**Comment by purofle** [comment]
不属于 nb4a 自身问题

**Comment by lyx32** [comment]
结案，手工把文件权限给了，就正常了。

**Comment by beyondth** [comment]
> 结案，手工把文件权限给了，就正常了。

请问是什么权限呢？
我也遇到一样的问题了，
两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置

**Comment by lyx32** [comment]
> > 结案，手工把文件权限给了，就正常了。
> 
> 请问是什么权限呢？ 我也遇到一样的问题了， 两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置，clash都没问题。

不是权限问题。我发现只要成功链接一次，后面至少3-7天用不了（锁屏直接失效）。
后面我发现在另外一个有公网的路由器上开sockt5端口，每次都可以链接成功并且能正常响应耗时，但是还是用不了。。。
最后的最后，我放弃了。还是用的其他app，连其他的协议。这个app佛系随缘吧。

**Comment by beyondth** [comment]
> > > 结案，手工把文件权限给了，就正常了。
> > 
> > 
> > 请问是什么权限呢？ 我也遇到一样的问题了， 两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置，clash都没问题。
> 
> 不是权限问题。我发现只要成功链接一次，后面至少3-7天用不了（锁屏直接失效）。 后面我发现在另外一个有公网的路由器上开sockt5端口，每次都可以链接成功并且能正常响应耗时，但是还是用不了。。。 最后的最后，我放弃了。还是用的其他app，连其他的协议。这个app佛系随缘吧。

最好是能把问题原因找到，很多手机clash用不了只能用这个

**Comment by lyx32** [comment]
> > > > 结案，手工把文件权限给了，就正常了。
> > > 
> > > 
> > > 请问是什么权限呢？ 我也遇到一样的问题了， 两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置，clash都没问题。
> > 
> > 
> > 不是权限问题。我发现只要成功链接一次，后面至少3-7天用不了（锁屏直接失效）。 后面我发现在另外一个有公网的路由器上开sockt5端口，每次都可以链接成功并且能正常响应耗时，但是还是用不了。。。 最后的最后，我放弃了。还是用的其他app，连其他的协议。这个app佛系随缘吧。
> 
> 最好是能把问题原因找到，很多手机clash用不了只能用这个

在vps上多装几个协议就可以了。我就是，路由器用hysteria，手机用xray

**Comment by beyondth** [comment]
> > > > > 结案，手工把文件权限给了，就正常了。
> > > > 
> > > > 
> > > > 请问是什么权限呢？ 我也遇到一样的问题了， 两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置，clash都没问题。
> > > 
> > > 
> > > 不是权限问题。我发现只要成功链接一次，后面至少3-7天用不了（锁屏直接失效）。 后面我发现在另外一个有公网的路由器上开sockt5端口，每次都可以链接成功并且能正常响应耗时，但是还是用不了。。。 最后的最后，我放弃了。还是用的其他app，连其他的协议。这个app佛系随缘吧。
> > 
> > 
> > 最好是能把问题原因找到，很多手机clash用不了只能用这个
> 
> 在vps上多装几个协议就可以了。我就是，路由器用hysteria，手机用xray

其中一台服务器，所有协议都不行啊，另一台所有配置都一样，结果能用，太奇怪了！

**Comment by lyx32** [comment]
> > > > > > 结案，手工把文件权限给了，就正常了。
> > > > > 
> > > > > 
> > > > > 请问是什么权限呢？ 我也遇到一样的问题了， 两台机子完全一样的配置，其中一台机子每个协议都显示连接被重置，clash都没问题。
> > > > 
> > > > 
> > > > 不是权限问题。我发现只要成功链接一次，后面至少3-7天用不了（锁屏直接失效）。 后面我发现在另外一个有公网的路由器上开sockt5端口，每次都可以链接成功并且能正常响应耗时，但是还是用不了。。。 最后的最后，我放弃了。还是用的其他app，连其他的协议。这个app佛系随缘吧。
> > > 
> > > 
> > > 最好是能把问题原因找到，很多手机clash用不了只能用这个
> > 
> > 
> > 在vps上多装几个协议就可以了。我就是，路由器用hysteria，手机用xray
> 
> 其中一台服务器，所有协议都不行啊，另一台所有配置都一样，结果能用，太奇怪了！

1.是不是被墙了。
2.是不是防火墙没放（不过一般不会是这个问题）。
3.是不是只有ipv6
