### ISSUE TITLE
BUG: 订阅自动更新不正常

### ISSUE THREAD

**Issue by stoneaw** [MatsuriDayo/NekoBoxForAndroid#423]
设定自动更新及自动更新间隔后，在设定的自动更新间隔到了之后，打开软件界面时，如果手机并没有联网，会闪出一条抓取不到连接那样的信息，然后这时再联网，软件也不会更新订阅，要等下一个更新间隔。
如果手机一直是联网状态，那么这个自动更新，有时成功，有时不成功，多数情况不成功，不成功时也是闪出一条抓取不到链接的信息。而订阅的链接，我在浏览器打开，每次都是成功的。
另外一个订阅被墙了，我设置成仅在连接时更新（这个选项意思大概是连接VPN情况下更新），可是从来没见它更新过，也没有出错信息，每次都是我手动更新。

**Comment by Choicc** [comment]
安卓14,设置的60分钟自动更新,基本上都没有成功过,有时候重新进入软件界面才会弹一下更新失败的弹窗
