### ISSUE TITLE
将 连接测试 放到主界面

### ISSUE THREAD

**Issue by JUST-INTJ** [MatsuriDayo/NekoBoxForAndroid#432]
## 描述建议
受每日高峰时间影响，机场会出现周期性波动。要手动测试来进行切换，这是个常用的功能。比`添加节点` `搜索` 更实用。
## 建议的必要性
将 `连接测试` 放到主界面中。最好能自动测试😁😁，像clash一样，我认为这是大家clash这么受新手 老手欢迎的一大原因。

**Comment by purofle** [comment]
不打算对 UI 进行更改。
