### ISSUE TITLE
BUG: 1.3.0版本打开闪退

### ISSUE THREAD

**Issue by GH6324** [MatsuriDayo/NekoBoxForAndroid#439]
回退到1.2.9版本就没有问题

附上闪退日志

[NB4A Crash 8947462978332388610.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13416753/NB4A.Crash.8947462978332388610.log)

**Comment by ycuso4y** [comment]
同问题

**Comment by HATOSHAH** [comment]
I have the same problem

**Comment by flin-ux** [comment]
一样的问题

**Comment by AnnieSmile** [comment]
一样的问题

**Comment by purofle** [comment]
1.3.0 版本数据库与老版本存在已知兼容性问题。
临时解决方法：降级 1.2.9 导出配置后升级 1.3.0 并清除软件数据，导出老配置

**Comment by jiamei11** [comment]
一样

**Comment by HATOSHAH** [comment]
Please release a new update as soon as possible to fix this bug. I have been waiting for a new update of Nekobox for a long time.

**Comment by TheInterestingSoul** [comment]
> 1.3.0 版本数据库与老版本存在已知兼容性问题。 临时解决方法：降级 1.2.9 导出配置后升级 1.3.0 并清除软件数据，导出老配置

哥们你逗我吗，安卓13就已经不允许`adb pm`降级安装了

**Comment by henqin111111** [comment]
我也是同样闪退，在pixel7上（安卓14）使用各种版本都闪退。在pixel3上使用不会（安卓12）

**Comment by henqin111111** [comment]
并且谷歌商店里提示“在你的国家不支持下载安装”，系统改为繁体后仍然闪退。
