### ISSUE TITLE
1.3.0版本vless无网，但是放到v2Rayng中却有网

### ISSUE THREAD

**Issue by tonydong1975** [MatsuriDayo/NekoBoxForAndroid#450]
## 描述问题

预期行为：![IMG_20231124_155805.jpg](https://pic.ziyuan.wang/2023/11/24/guest_1d3dd2316461b.jpg)

![Screenshot_2023-11-24-16-15-00-52_99c04817c0de5652397fc8b56c3b3817.jpg](https://pic.ziyuan.wang/2023/11/24/guest_51ff57cf5b1b5.jpg)

实际行为：

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by tonydong1975** [comment]
![Screenshot_2023-11-24-16-03-03-29_c8c413cbdde2659431e41a03d647cf5f.jpg](https://pic.ziyuan.wang/2023/11/24/guest_333a13f562b44.jpg)

**Comment by purofle** [comment]
这不是连接成功吗

**Comment by tonydong1975** [comment]
虽然连接成功 但是 浏览器浏览网页打不开，放到v2Rayng里没问题

**Comment by purofle** [comment]
> 虽然连接成功 但是 浏览器浏览网页打不开，放到v2Rayng里没问题

握手成功表示 nb4a 已经可以正常建立 http 连接，无法打开网页请找其他方面问题。
