### ISSUE TITLE
BUG: 1.3.0版本出现跳转分享页面的问题

### ISSUE THREAD

**Issue by sudbxbxkkk** [MatsuriDayo/NekoBoxForAndroid#451]
打开应用就会跳转到分享

## 如何复现
可能因订阅过多导致

https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/149476160/49075b4e-979d-400c-baf4-223a0c9bf9ba

**Comment by MrAbolfazlNorouzi** [comment]
I have same problem

**Comment by purofle** [comment]
#447
