### ISSUE TITLE
BUG: 无法导入订阅

### ISSUE THREAD

**Issue by chenshiba000** [MatsuriDayo/NekoBoxForAndroid#455]
## 描述问题

实际行为：导入订阅失败，在clash for android可以导入，尝试不同订阅后都是如此。是否为鸿蒙4系统原因？
![Screenshot_20231126_003223_moe nb4a](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/83282317/f243922e-b768-4c9d-bc09-c537545daa7e)

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by purofle** [comment]
导入订阅是在右边选择组 添加 类型选择订阅
