### ISSUE TITLE
请增加自动选择最低延迟

### ISSUE THREAD

**Issue by National164** [MatsuriDayo/NekoBoxForAndroid#460]
## 描述建议
可参考隔壁的Hiddify，定时测试并选择最低延迟选定
## 建议的必要性
此功能对体验提升非常大，如果是目前的话需要在应用内测试一次后再进行选定步骤麻烦许多，而且部分机场节点不稳定测试的数据也会不具备时效性。强烈建议支持这个功能

**Comment by AthendX** [comment]
同求

**Comment by purofle** [comment]
不会加入 之前已经有过类似issue
