### ISSUE TITLE
能否将url test置于顶部或者一级菜单

### ISSUE THREAD

**Issue by bupt2017** [MatsuriDayo/NekoBoxForAndroid#475]
## 描述建议
将url test置于顶部以便于经常测试

## 建议的必要性
对于节点比较多的使用者尤其是机场用户来说使用url test或者tcping可能会比较多。因为不确定哪个节点可用或者延迟低，所以需要经常测试。
目前的tcping和url test需要三次点击才能达到。能否改进成像clash for Android一样直接置于顶部（一次点击），或者像v2rayng一样放在一级菜单（点击两次）。
![Screenshot_2023-12-09-14-37-38-248_com.github.kr328.clash-1-1.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/29458450/d205694a-9997-4884-b516-da04a40561f5)

当然将url test和tcping放在connection test中是很规范的，但是因为每次都需要点击很多次，所以希望开发者考虑一下。

**Comment by JUST-INTJ** [comment]
#432
