### ISSUE TITLE
如何程序化的生成可分享的 SN link 或者 QRCode? 

### ISSUE THREAD

**Issue by somehow22** [MatsuriDayo/NekoBoxForAndroid#478]
## Description suggestions
自建的代理，希望能配置服务的时候，直接生成可以导入的字符串或者二维码，方便客户端操作。
但是我尝试了在客户端生成 json 然后命令行 qrencode 生成的图片，无法导入
更不用说 SN Link 了，完全不知道咋生成字串

## Necessity of recommendations
方便客户端操作

**Comment by purofle** [comment]
二维码的格式是分享链接，你可以在任意代理软件里手动输入信息后拿到
