### ISSUE TITLE
your app is too old, please update ?? what?????

### ISSUE THREAD

**Issue by rony432** [MatsuriDayo/NekoBoxForAndroid#479]
![image](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/126810356/d3a6bcb5-c117-469b-9d4e-cafedc591d22)
why there is force update alert. 
why app will stop working at 2024-01-10 ?

please disable it

**Comment by rony432** [comment]
FIX
/app/src/main/java/io/nekohasekai/sagernet/ui/MainActivity.kt

in MainActivity.kt

find this
`val sdf = SimpleDateFormat("yyyy-MM-dd")
val now = System.currentTimeMillis()
val expire = Libcore.getExpireTime() * 1000
val dateExpire = Date(expire)
val build = Libcore.getBuildTime() * 1000
val dateBuild = Date(build)

var text: String? = null
if (now > expire) {
    text = getString(
        R.string.please_update_force, sdf.format(dateBuild), sdf.format(dateExpire)
    )
} else if (now > (expire - 2592000000)) {
    // 30 days remind :D
    text = getString(
        R.string.please_update, sdf.format(dateBuild), sdf.format(dateExpire)
    )
}
`

change to this
`val sdf = SimpleDateFormat("yyyy-MM-dd")
val now = System.currentTimeMillis()
val expire = Libcore.getExpireTime() * 1000
val dateExpire = Date(expire)
val build = Libcore.getBuildTime() * 1000
val dateBuild = Date(build)

// Commenting out the update alert logic
/*
var text: String? = null
if (now > expire) {
    text = getString(
        R.string.please_update_force, sdf.format(dateBuild), sdf.format(dateExpire)
    )
} else if (now > (expire - 2592000000)) {
    // 30 days remind :D
    text = getString(
        R.string.please_update, sdf.format(dateBuild), sdf.format(dateExpire)
    )
}
*/
`
In this modification, I've commented out the entire if-else block. This means the part of the code responsible for checking the current time against the expiration time and setting the update alert message will be ignored during execution.

and. there is a reason people use old versions of apps,
please change it to "there is a update, do you want to update" and a setting to disable update check.



thank you. now im going to build my own to use it for ever :)

**Comment by purofle** [comment]
Removed in new version

**Comment by rony432** [comment]
thank you, you are a nice dev
