### ISSUE TITLE
BUG: 运行生成 libcore.aar错误

### ISSUE THREAD

**Issue by MingtimeThis** [MatsuriDayo/NekoBoxForAndroid#493]
运行在 mac m2    go version go1.21.5 darwin/arm64

NekoBoxForAndroid % ./run lib core                  
./run: line 5: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
>> buildScript/lib/core.sh
~/vpn ~/vpn/NekoBoxForAndroid
~/vpn/sing-box-extra ~/vpn ~/vpn/NekoBoxForAndroid
HEAD is now at 5b03ea2 1.6.4-3
~/vpn ~/vpn/sing-box-extra
~/vpn/sing-box ~/vpn ~/vpn/sing-box-extra
HEAD is now at 64f4eed clashapi: fix panic
~/vpn ~/vpn/sing-box-extra
~/vpn/sing-quic ~/vpn ~/vpn/sing-box-extra
fatal: unable to access 'https://github.com/MatsuriDayo/sing-quic.git/': Failed to connect to github.com port 443 after 75006 ms: Couldn't connect to server
Cloning into 'gomobile'...
remote: Enumerating objects: 10059, done.
remote: Total 10059 (delta 0), reused 0 (delta 0), pack-reused 10059
Receiving objects: 100% (10059/10059), 6.41 MiB | 4.48 MiB/s, done.
Resolving deltas: 100% (6293/6293), done.
~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd ~/vpn/NekoBoxForAndroid/libcore
~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd/gomobile ~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd ~/vpn/NekoBoxForAndroid/libcore
~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd ~/vpn/NekoBoxForAndroid/libcore
~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd/gobind ~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd ~/vpn/NekoBoxForAndroid/libcore
~/vpn/NekoBoxForAndroid/libcore/gomobile/cmd ~/vpn/NekoBoxForAndroid/libcore
~/vpn/NekoBoxForAndroid/libcore
realpath: .build: No such file or directory
flag provided but not defined: -cache
usage: gomobile bind [-target android|ios|iossimulator|macos|maccatalyst] [-bootclasspath <path>] [-classpath <path>] [-o output] [build flags] [package]

Bind generates language bindings for the package named by the import
path, and compiles a library for the named target system.

The -target flag takes either android (the default), or one or more
comma-delimited Apple platforms (ios, iossimulator, macos, maccatalyst).

For -target android, the bind command produces an AAR (Android ARchive)
file that archives the precompiled Java API stub classes, the compiled
shared libraries, and all asset files in the /assets subdirectory under
the package directory. The output is named '<package_name>.aar' by
default. This AAR file is commonly used for binary distribution of an
Android library project and most Android IDEs support AAR import. For
example, in Android Studio (1.2+), an AAR file can be imported using
the module import wizard (File > New > New Module > Import .JAR or
.AAR package), and setting it as a new dependency
(File > Project Structure > Dependencies).  This requires 'javac'
(version 1.8+) and Android SDK (API level 16 or newer) to build the
library for Android. The ANDROID_HOME and ANDROID_NDK_HOME environment
variables can be used to specify the Android SDK and NDK if they are
not in the default locations. Use the -javapkg flag to specify the Java
package prefix for the generated classes.

By default, -target=android builds shared libraries for all supported
instruction sets (arm, arm64, 386, amd64). A subset of instruction sets
can be selected by specifying target type with the architecture name. E.g.,
-target=android/arm,android/386.

For Apple -target platforms, gomobile must be run on an OS X machine with
Xcode installed. The generated Objective-C types can be prefixed with the
-prefix flag.

For -target android, the -bootclasspath and -classpath flags are used to
control the bootstrap classpath and the classpath for Go wrappers to Java
classes.

The -v flag provides verbose output, including the list of packages built.

The build flags -a, -n, -x, -gcflags, -ldflags, -tags, -trimpath, and -work
are shared with the build command. For documentation, see 'go help build'.
哪位大佬能指点一下怎么改不

**Comment by xchacha20-poly1305** [comment]
> fatal: unable to access 'https://github.com/MatsuriDayo/sing-quic.git/': Failed to connect to github.com port 443

**Comment by purofle** [comment]
请使用 nekobox4android 自己的脚本安装 gomobile 或者自行修改编译脚本
