### ISSUE TITLE
BUG: ECH parameter can not be set

### ISSUE THREAD

**Issue by dill-shower** [MatsuriDayo/NekoBoxForAndroid#497]
Step 1
Open config and enable ech
![step1](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/114938733/4b43073d-1e35-4ae8-9a56-640111d23073)

Step 2
Press apply

Step 3
Open config now
![step2](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/114938733/0fd5b404-9ba5-44e6-b371-45d290de88d5)

ECH not enabled...

ECH parameter set to NO automatic if press aply?

**Comment by valuables3327** [comment]
same issue

**Comment by dill-shower** [comment]
I'm not sure that it is worth creating a new issue, but Sing-Box in 1.8.0 added new UTLS for Ech

SINCE SING-BOX 1.8.0

 Chrome_psk
 Chrome_psk_shuffle
 chrome_padding_psk_shuffle
 Chrome_pq
 chrome_pq_psk

https://sing-box.saigernet.org/configuration/shahed/tls/#utls

The possibility of their choice will be useful when using ECH in order to be even more like a real Chrome
