### ISSUE TITLE
BUG: 安卓14下的分应用代理看不到应用

### ISSUE THREAD

**Issue by rickcui** [MatsuriDayo/NekoBoxForAndroid#498]
三星手机，升级了OneUI6（安卓版本从13升级为了14）后，在分应用代理内，看不到所有的应用程序，程序列表显示为空白，点上显示系统应用也是一样，并且在搜索框中搜索特定程序，程序列表也是空白，希望能改正此bug，谢谢！

**Comment by purofle** [comment]
请提供log

**Comment by bupt2017** [comment]
手机请授予 获取应用列表权限

**Comment by rickcui** [comment]
果然是权限的问题，已搞定，谢谢！
