### ISSUE TITLE
BUG: 同一个VPS  HY2在手机端看不了奈菲非自制剧，用VLESS 就可以看。

### ISSUE THREAD

**Issue by jwmjazz** [MatsuriDayo/NekoBoxForAndroid#501]
## 描述问题
一个VPS  HY2在手机端看不了奈菲非自制剧，在电脑端就可以看，配置文件相同
另一个VPS  HY2 在手机端和电脑端都可以看。
预期行为：
希望找到原因
实际行为：

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by MiniKoro** [comment]
这你应该去hy那里问
