### ISSUE TITLE
BUG: trojan 和 shadowsocks libev 在sagernet 能连，在nekobox 无法连接

### ISSUE THREAD

**Issue by 142857X1** [MatsuriDayo/NekoBoxForAndroid#504]
## Describe the problem

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by 142857X1** [comment]
我尝试了V8a  V7a 都连不上好像以前的茉莉就连不上，手机是华为的麒麟980

**Comment by purofle** [comment]
非软件问题

**Comment by 142857X1** [comment]
> 非软件问题

应是软件问题，我打开设置了 中的 像sagernet一样显示底栏 就能正常链接了
