### ISSUE TITLE
设置IPv6优先，并没有使用服务器的IPv6地址去连接

### ISSUE THREAD

**Issue by maskedeken** [MatsuriDayo/NekoBoxForAndroid#51]
**描述问题**
我的服务器都配有IPv4和IPv6，我的本机也是双栈环境，在设置IPv6优先情况下，并没有优先使用服务器的IPv6地址去连接
预期行为：
设置IPv6优先，能够像Matsuri一样，优先使用服务器的IPv6地址去连接
实际行为：
设置IPv6优先，并没有使用服务器的IPv6地址去连接
**如何复现**

提供有帮助的截图，录像，文字说明，订阅链接等。

**日志**

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by maskedeken** [comment]
敏感信息已隐藏
[NB4A 6472073637343320481.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/11086774/NB4A.6472073637343320481.log)

**Comment by maskedeken** [comment]
懂了，resolveDestination要打开，才能IPv6优先。但在Matsuri中不用打开

**Comment by malikshi** [comment]
I think we need additional options for type of ipv6 or ipv4 for node/proxy/

Set route is for dns route strategy
![Screenshot_2023-04-14-17-43-30-357-edit_moe nb4a](https://user-images.githubusercontent.com/9080737/232024002-8f2b1bed-0272-4391-80a1-5fa3e7df7e60.jpg)
 Current exported file still ipv4 its should be ipv6
![Screenshot_2023-04-14-17-44-33-745-edit_com foxdebug acodefree](https://user-images.githubusercontent.com/9080737/232024224-13024c64-3146-4f8c-a2ed-5ca48f09d0be.jpg)
 
Add menu settings type ipv6/ipv4 for node/proxy would be good. So users no need to create and edit custom config.
If am using current base config ipv6 having issues and score 9/10 from test-ipv6
