### ISSUE TITLE
BUG: NekoBoxForAndroid1.3.0 更新订阅跳出错框。装回1.2.9同订阅更新正常

### ISSUE THREAD

**Issue by qc2t** [MatsuriDayo/NekoBoxForAndroid#511]
## 描述问题：NekoBoxForAndroid1.3.0 更新订阅跳出错框。装回1.2.9同订阅更新正常

预期行为：修复

实际行为：跳出错框

## 如何复现：见附图
![Screenshot_20240102-231740_NekoBox~2](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/12804726/f736f92f-f51c-48d4-ab9c-bd89ee6d8beb)

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by TDYQ-Liu** [comment]
我也遇到了

**Comment by purofle** [comment]
非程序问题
