### ISSUE TITLE
[Feature Request] The useful feature of enhance resolve of server domain

### ISSUE THREAD

**Issue by HATOSHAH** [MatsuriDayo/NekoBoxForAndroid#53]
Hello, please add enhance resolve of server domain to nekobox

![IMG_20230328_053042_693](https://user-images.githubusercontent.com/86057784/228108333-72c337ce-9c2f-43b3-990c-80c8f9b2939d.jpg)

**Comment by Ght55** [comment]
Nekobox  not working cludeflare domain 
Why???????
Test config  very slow  
Vmess  Vless Trojan shadowsocks ssh  http 
Working very bad into client  Nekobox 
Matsuri ok✅️

**Comment by Ght55** [comment]
![Screenshot_20230328_201317_Matsuri](https://user-images.githubusercontent.com/129114974/228310282-211f8a9e-1838-4d0a-887e-3c304dcb08b5.jpg)
Pls add to Nekobox  thanks. New. Version
