### ISSUE TITLE
Please make app Nekobox for Smart tv (android TV 10, Google TV)

### ISSUE THREAD

**Issue by vuducdong** [MatsuriDayo/NekoBoxForAndroid#531]
## Description suggestions

I tried installing version NB4A-1.3.0-armeabi-v7a.apk, installed it, but can't use it, can't create configuration (can't press the add button), it seems this version is only for users. smartphones.

Please make app Nekobox for Smart tv (android TV 10, Google TV)

Thank you!

**Comment by arash88** [comment]
+1

**Comment by livingroot** [comment]
+

**Comment by authorless** [comment]
+1

**Comment by ivanov-24** [comment]
+1

**Comment by serjevski** [comment]
+1

**Comment by QQpwnz** [comment]
+1

**Comment by supra144** [comment]
+

**Comment by steleal** [comment]
+1

**Comment by NeeCo56** [comment]
+1

**Comment by NeeCo56** [comment]
I use an air mouse or just connect a mouse to a smart TV

**Comment by DmitriiSukhomlinov** [comment]
+1

**Comment by MakotoU7** [comment]
> I use an air mouse or just connect a mouse to a smart TV. But it would be cool if there was support for smart TV

So you can use it on android TV, but with a mouse, right?
