### ISSUE TITLE
BUG: Nekobox 1.3.0 版本更换分组后闪退，并无法再进入应用。

### ISSUE THREAD

**Issue by Honore-Pelchat** [MatsuriDayo/NekoBoxForAndroid#543]
## Describe the problem

Expected behavior:更换分组。

Actual behavior:退出，显示崩溃日志。

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/115097603/d26a09d0-dd5f-4197-ba1b-bcd3950ea31a

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.
[NB4A Crash 626428635113420966.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/14166263/NB4A.Crash.626428635113420966.log)

**Comment by TheInterestingSoul** [comment]
+1,我也挂了
