### ISSUE TITLE
取消强制更新弹窗

### ISSUE THREAD

**Issue by skyhx** [MatsuriDayo/NekoBoxForAndroid#595]
## 描述建议
取消强制更新弹窗

## 建议的必要性
老版本既然能用就没必要非要用最新版本，强制更新有点儿太强制了
既然仓库资产里面有历史版本，却又必须强制更新，那历史版本也就没有存在的意义

**Comment by Mronezc** [comment]
刚才看了一下提交，取消了但是他没回复你哈哈哈

**Comment by skyhx** [comment]
> 刚才看了一下提交，取消了但是他没回复你哈哈哈

从哪个版本开始不强制更新了？

**Comment by mbicc** [comment]
被更新了1.31,然后灭屏休眠会自动关了

**Comment by oplle** [comment]
我是顺便把nekobox当防火墙使用，通过应用规则、域名规则、广告规则和ip规则阻止某些app包括系统app联网，希望不要强制更新，我的节点协议很稳定，规则也写的比较复杂，而sing-box从1.7.0开始有了很多变化，我想停留在1.6及以下版本，希望不要在后续强制更新版本
