### ISSUE TITLE
BUG: 路由规则有且仅有geosite ip cn绕过的情况下，国内流量被代理到远程服务器

### ISSUE THREAD

**Issue by NikoCat233** [MatsuriDayo/NekoBoxForAndroid#614]
## 描述问题

预期行为：geoip:cn匹配国内ip流量直连处理

实际行为：国内流量被代理

## 如何复现

这是由nb4a生成的route配置文件

  "route": {
    "auto_detect_interface": true,
    "rule_set": [
      {
        "format": "binary",
        "path": "/storage/emulated/0/Android/data/moe.nb4a/files/ruleSets/geosite-category-ads-all.srs",
        "tag": "geosite:category-ads-all",
        "type": "local"
      },
      {
        "format": "binary",
        "path": "/storage/emulated/0/Android/data/moe.nb4a/files/ruleSets/geosite-microsoft.srs",
        "tag": "geosite:microsoft",
        "type": "local"
      },
      {
        "format": "binary",
        "path": "/storage/emulated/0/Android/data/moe.nb4a/files/ruleSets/geosite-cn.srs",
        "tag": "geosite:cn",
        "type": "local"
      },
      {
        "format": "binary",
        "path": "/storage/emulated/0/Android/data/moe.nb4a/files/ruleSets/geoip-cn.srs",
        "tag": "geoip:cn",
        "type": "local"
      }
    ],
    "rules": [
      {
        "outbound": "dns-out",
        "port": [
          53
        ]
      },
      {
        "inbound": [
          "dns-in"
        ],
        "outbound": "dns-out"
      },
      {
        "outbound": "block",
        "rule_set": [
          "geosite:category-ads-all"
        ]
      },
      {
        "domain_suffix": [
          "appcenter.ms",
          "app-measurement.com",
          "firebase.io",
          "crashlytics.com",
          "google-analytics.com"
        ],
        "outbound": "block",
        "rule_set": []
      },
      {
        "outbound": "proxy",
        "rule_set": [
          "geosite:microsoft"
        ]
      },
      {
        "domain_suffix": [
          "googleapis.cn"
        ],
        "outbound": "proxy",
        "rule_set": []
      },
      {
        "outbound": "bypass",
        "rule_set": [
          "geosite:cn"
        ]
      },
      {
        "outbound": "bypass",
        "rule_set": [
          "geoip:cn"
        ],
        "rule_set_ipcidr_match_source": true
      },
      {
        "ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ],
        "outbound": "block",
        "source_ip_cidr": [
          "224.0.0.0/3",
          "ff00::/8"
        ]
      }
    ]
  }
}
## 日志
日志难以进行脱敏处理，稍后补加

**Comment by NikoCat233** [comment]
路由库采用loy并且保持最新

**Comment by NikoCat233** [comment]
经尝试，在路由规则中仅保留geoip:cn bypass,
所有国内ip流量无一幸免，全部代理
101.35.76.32:8080为例

**Comment by NikoCat233** [comment]
在nekobox 129上 geoip:cn表现正常

**Comment by NikoCat233** [comment]
另外131生成的备份配置文件无法导入129

**Comment by NikoCat233** [comment]
无效issue，请忽略

**Comment by zx3777** [comment]
请问为什么会出现这种情况呢？
