### ISSUE TITLE
BUG: 手机配置有加密dns的情况下，会无法访问网络，提示当然网络无法访问加密DNS

### ISSUE THREAD

**Issue by twopuddings** [MatsuriDayo/NekoBoxForAndroid#616]
## 描述问题

预期行为：配置有加密DNS的情况下，启动代理可以正常访问网络

实际行为：配置有加密DNS的情况下，启动代理无法访问网络，需要关闭加密DNS才行

![Screenshot_20240323_113426_com huawei browser_edit_109527303284329](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/21051481/d8a38b07-ba4b-43e8-b271-c0fe1607cc05)

**Comment by CharlesLocke** [comment]
![2024-03-30_21-50-20](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/22140090/cfc1325f-e603-42be-8e6a-d7ff94d95129)

**Comment by CharlesLocke** [comment]
![2024-03-30_21-51-37](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/22140090/63ea869d-f2bc-4793-8e1c-62e532397d57)
