### ISSUE TITLE
Fragment 

### ISSUE THREAD

**Issue by Graveyard9988** [MatsuriDayo/NekoBoxForAndroid#619]
Iranian users need to enable fragment feature in Nekobox

Unfortunately i'm not programmer 
but Here's exact source code of feature "Fragment":
https://github.com/maskedeken/sing-box/commit/a42d2e6fd16d9bd359c828e9d527430e05d1ed4b

Here's the screenshot of feature:
![Screenshot_20240323_113516_NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/116078041/e5d3e3a5-73eb-4042-b898-3c6bb45cd039)

We urgently need "fragment" in your app.

Regards

**Comment by ca3tiel** [comment]
Please add the fragment feature to the application. Almost all similar applications on Android, Windows, and even iOS and Mac added this feature a long time ago. More than 80% of different operators in Iran do not support IPv6, and purchased domains are filtered in less than 2 hours, and even UDP ports are closed or have a lot of problems, and almost the only way to connect It works well to use fragment.
Best Regards
