### ISSUE TITLE
BUG: clash订阅链接的分流规则不生效

### ISSUE THREAD

**Issue by ZerOri** [MatsuriDayo/NekoBoxForAndroid#640]
## 描述问题

预期行为：
填入使用了订阅转换的clash链接，分流规则不加载，只有默认的proxy和global两个规则，是app不支持订阅转换链接还是需要额外设置？
app版本：1.2.9

实际行为：
如图，请大佬指教。

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。
![Screenshot_2024-04-21-07-57-01-976_moe.nb4a-edit.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/46775615/943c6a51-e804-4fbe-a420-f37879eea3e9)

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by naloder** [comment]
clash代理的规则和singbox类完全不通用，且只是兼容订阅解析而已，请自行设置路由规则

**Comment by ZerOri** [comment]
> clash代理的规则和singbox类完全不通用，且只是兼容订阅解析而已，请自行设置路由规则

原来如此，谢谢解答
