### ISSUE TITLE
BUG: 挂后台自己停止

### ISSUE THREAD

**Issue by 2247ds** [MatsuriDayo/NekoBoxForAndroid#644]
## 描述问题
协议是hy2，设置好锁后台和电池优化但无效，转成系统app后还是会停止
预期行为：

实际行为：

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。

## 日志
[NB4A 2184413928642940667.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/15142355/NB4A.2184413928642940667.log)

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by hiccup9** [comment]
遇到同样的问题

**Comment by y2485871697** [comment]
我也是
1.3.1
也是歇斯底里2
![Screenshot_20240508-090107_NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/126750630/a48efc97-283b-45e1-a25c-04afe049c762)

**Comment by zazitufu** [comment]
换回github版本的1.2.9 养老吧
