### ISSUE TITLE
本软件谷歌商店被第三方挂了广告！

### ISSUE THREAD

**Issue by silencebbb** [MatsuriDayo/NekoBoxForAndroid#654]
本软件谷歌商店被第三方挂了广告！也许订阅都被偷了！
这个商店不归作者管真的很奇葩！
装了开源版本也没法阻止商店更新！

![Screenshot_2024-05-06-22-56-34-782_moe nb4a](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/26780624/b4e1c065-25bf-4acd-96cf-6c39c8c0ffa3)

**Comment by gsszxaf** [comment]
装1.3.1版完美解决

**Comment by JSSBach** [comment]
这也能被偷家…

**Comment by wintertee** [comment]
目前 Action 构建的签名和 Google Play 使用的签名一致，是否考虑更换签名，避免 Google Play 那边恶意修改高版本号，导致Google Play后台自动更新？

**Comment by Jinnrry** [comment]
是否考虑换个软件名or换个包名？ 不然别人发个高版本号直接把程序更新掉了呀

**Comment by fsxitutu** [comment]
> 装1.3.1版完美解决

Google play版本的版本号已经是1.3.1了，而且还改了名字。暂时只能关闭自动更新处理。

**Comment by WonSintak** [comment]
![Screenshot_20240508_112118_SAI](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/133520543/e2357dd4-709a-437b-b24d-03bed55f3af8)
卸载之后重新安装显示这个。。服了。。。

**Comment by avenger2005** [comment]
如何备份nekobox的现有设置？以便重装导入
另外怎么禁用Googleplay更新这个app

**Comment by fsxitutu** [comment]
> ![Screenshot_20240508_112118_SAI](https://private-user-images.githubusercontent.com/133520543/328743664-e2357dd4-709a-437b-b24d-03bed55f3af8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjI3NjEsIm5iZiI6MTcxNTIyMjQ2MSwicGF0aCI6Ii8xMzM1MjA1NDMvMzI4NzQzNjY0LWUyMzU3ZGQ0LTcwOWEtNDM3Yi1iMjRkLTAzYmVkNTVmM2FmOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMjQxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTQ1N2ZmYTA0M2UzZDczMjU4MTgxZWE0NjY1M2NjOGViZjdhYWQ4OWRjMGUwZWY0YTY4ODFjODhmMDgzOTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iydBnYeglFJzYE7v7lBxhHG56vRuIe3KY8UrHtFu8co) 卸载之后重新安装显示这个。。服了。。。

我是用核心破解才安上github版本的😭

**Comment by my1996** [comment]
> 如何备份nekobox的现有设置？以便重装导入
> 另外怎么禁用Googleplay更新这个app

工具 中有 备份选项，

你在这发不如直接去Google

**Comment by Billyas** [comment]
能不能投诉举报下 play 商店的版本呢？🥲

**Comment by silencebbb** [comment]
作者又弃坑了？？？

**Comment by WROIATE** [comment]
> 这个会有什么安全隐患吗？之前 app 里记录的账号信息会不会被收集了？

我意识到这个问题的时候已经马上去把代理的密码改了

**Comment by lp123sun** [comment]
已更换xchacha20-poly1305/husi，用着也还不错

**Comment by xiaorong61** [comment]
都被偷相当于没被偷 🤣

**Comment by qwIvan** [comment]
请问play上的版本安全吗？刚刚装了用了一下，会不会我的自建梯子信息都被上报了？

**Comment by xiaorong61** [comment]
> 请问play上的版本安全吗？刚刚装了用了一下，会不会我的自建梯子信息都被上报了？

害怕的话可以到机场网站重建订阅连接，自建的重置密码和端口
