### ISSUE TITLE
BUG: 特定DNS设置有时无法连接节点

### ISSUE THREAD

**Issue by CodingMoeButa** [MatsuriDayo/NekoBoxForAndroid#665]
## 描述问题

使用特定DNS设置时有时无法连接到节点服务器。

预期行为：

连接到节点。

实际行为：

连接超时。

## 如何复现

Hysteria2节点服务器支持双栈，将客户端“域名策略（服务器地址）”设为`prefer_ipv6`并关闭“启用DNS路由”。

**Comment by zazitufu** [comment]
你的服务器是用IP还是用域名，用域名的话，同个域名是同时解析了IPv4和ipv6吗？

你设备使用的网络条件是什么？是蜂窝数据那样同时有ipv4、6吗？如果是连的某个wifi，那这个网有没有ipv6？

你使用的客户端是什么版本？github下载还是play商店下载？

建议把已知的信息都发出来，甚至日志（脱敏）。不然就是赛博算命了。

**Comment by CodingMoeButa** [comment]
> 你的服务器是用IP还是用域名，用域名的话，同个域名是同时解析了IPv4和ipv6吗？
> 
> 你设备使用的网络条件是什么？是蜂窝数据那样同时有ipv4、6吗？如果是连的某个wifi，那这个网有没有ipv6？
> 
> 你使用的客户端是什么版本？github下载还是play商店下载？
> 
> 建议把已知的信息都发出来，甚至日志（脱敏）。不然就是赛博算命了。

域名稳健解析，服务器是双栈。本地网络是双栈。Github下载的1.2.9。

**Comment by CodingMoeButa** [comment]
不期待解决此问题，故关闭。
