### ISSUE TITLE
BUG: Google play 上架同包名盗版app

### ISSUE THREAD

**Issue by RedSTARO** [MatsuriDayo/NekoBoxForAndroid#689]
## 描述问题

预期行为：Google play自动更新时发现的

实际行为：

## 如何复现

提供有帮助的截图，录像，文字说明，订阅链接等。![Screenshot_2024-06-01-16-31-54-405_com.miui.securitycenter.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/74100786/750e9de0-070e-4152-b500-852e3aacc825)

![Screenshot_2024-06-01-16-32-00-422_com.miui.securitycenter.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/74100786/6d71d98b-81d4-41ce-ac0e-c88d555a9e00)

![Screenshot_2024-06-01-16-32-11-964_moe.nb4a.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/74100786/7a339407-348b-4fd2-8f47-a155ac3d3608)

## 日志

如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by naloder** [comment]
已知 请参考其他issue 和readme说明

**Comment by 4SM** [comment]
请优先选择 f-droid. 获取应用程序。谢谢。
