### ISSUE TITLE
SplitHTTP 支持

### ISSUE THREAD

**Issue by tqangxl** [MatsuriDayo/NekoBoxForAndroid#713]
## 建议的必要性
[Xray-core v1.8.16](https://github.com/XTLS/Xray-core/releases/tag/v1.8.16)
SplitHTTP 传输方式 https://github.com/XTLS/Xray-core/pull/3412 https://github.com/XTLS/Xray-core/pull/3462 https://github.com/XTLS/Xray-core/discussions/716 @mmmray @RPRX @Fangliding
实现进一步的流量混淆有两种刚好相反的方式：多路复用 与 拆分连接，虽然现在只是逻辑拆分而没有实际拆分

SplitHTTP 使用 HTTP GET 长连接传输下行流量，使用多个 HTTP POST 请求传输上行流量，可以通过不支持 WebSocket、gRPC 的 CDN，实现与 Meek 相同的目标，但 SplitHTTP 是从零开始设计的全新传输方式，并非基于 Meek 修改而来，且 SplitHTTP 比 Meek 更简单、效率更高，详见文档 [英文（原生文档）](https://xtls.github.io/en/config/transports/splithttp.html) [中文（内容略有不同）](https://xtls.github.io/config/transports/splithttp.html)

此外，SplitHTTP 没有 WebSocket 的 ALPN 问题，这是一大优势，未来还会支持 HTTP/3

Features
HTTPUpgrade 使用自定义 headers 可以保持大小写 https://github.com/XTLS/Xray-core/pull/3427 https://github.com/XTLS/Xray-core/pull/3430 @mmmray @Fangliding
嗅探选项 domainsExcluded 可以使用正则表达式 https://github.com/XTLS/Xray-core/pull/3449 @Fangliding
Fixes
修复 Wireguard 入站的一个崩溃 https://github.com/XTLS/Xray-core/pull/3391 @yuhan6665
修复一处 UDP 内存泄露 https://github.com/XTLS/Xray-core/pull/3401 @isluckys
HTTPUpgrade 缓存可以正确释放 https://github.com/XTLS/Xray-core/pull/3428 @mmmray

**Comment by maskedeken** [comment]
NekoBox用的是sing-box内核，除非sing-box支持，否则用不了SplitHTTP

**Comment by xiaorong61** [comment]
> ## 描述建议
> ## 建议的必要性
> [Xray-core v1.8.16](https://github.com/XTLS/Xray-core/releases/tag/v1.8.16) SplitHTTP 传输方式 [XTLS/Xray-core#3412](https://github.com/XTLS/Xray-core/pull/3412) [XTLS/Xray-core#3462](https://github.com/XTLS/Xray-core/pull/3462) [XTLS/Xray-core#716](https://github.com/XTLS/Xray-core/discussions/716) @mmmray @RPRX @Fangliding 实现进一步的流量混淆有两种刚好相反的方式：多路复用 与 拆分连接，虽然现在只是逻辑拆分而没有实际拆分
> 
> SplitHTTP 使用 HTTP GET 长连接传输下行流量，使用多个 HTTP POST 请求传输上行流量，可以通过不支持 WebSocket、gRPC 的 CDN，实现与 Meek 相同的目标，但 SplitHTTP 是从零开始设计的全新传输方式，并非基于 Meek 修改而来，且 SplitHTTP 比 Meek 更简单、效率更高，详见文档 [英文（原生文档）](https://xtls.github.io/en/config/transports/splithttp.html) [中文（内容略有不同）](https://xtls.github.io/config/transports/splithttp.html)
> 
> 此外，SplitHTTP 没有 WebSocket 的 ALPN 问题，这是一大优势，未来还会支持 HTTP/3
> 
> Features HTTPUpgrade 使用自定义 headers 可以保持大小写 [XTLS/Xray-core#3427](https://github.com/XTLS/Xray-core/pull/3427) [XTLS/Xray-core#3430](https://github.com/XTLS/Xray-core/pull/3430) @mmmray @Fangliding 嗅探选项 domainsExcluded 可以使用正则表达式 [XTLS/Xray-core#3449](https://github.com/XTLS/Xray-core/pull/3449) @Fangliding Fixes 修复 Wireguard 入站的一个崩溃 [XTLS/Xray-core#3391](https://github.com/XTLS/Xray-core/pull/3391) @yuhan6665 修复一处 UDP 内存泄露 [XTLS/Xray-core#3401](https://github.com/XTLS/Xray-core/pull/3401) @isluckys HTTPUpgrade 缓存可以正确释放 [XTLS/Xray-core#3428](https://github.com/XTLS/Xray-core/pull/3428) @mmmray

我有个疑问，split 是否支持 mptcp 那种单连接拆分到单连接使得网络加速的功能？
