### ISSUE TITLE
BUG: 1.3.1及1.3.2版本使用wireguard协议，同配置下服务器地址填域名不可连接（指点击连接后一直处加载中，无错误日志），直接使用IP地址可正常使用。特别说明：本次测试基于软件默认设置下测试。

### ISSUE THREAD

**Issue by i-Eureka** [MatsuriDayo/NekoBoxForAndroid#785]
不过已有这类Issues被Close，https://github.com/MatsuriDayo/NekoBoxForAndroid/issues/676
如果需要特别设置是可以正常使用域名的话，请Close。

**Comment by PDxtXHd** [comment]
可以复现，而且解决方法很简单，把直连dns从local换成其他任意可用dns即可解决。1.3.2版本把这个默认值改成了腾讯的doh，但升级版本不会动这个配置。所以如果你是用1.3.2覆盖安装了1.3.1则仍然会有问题。作者close的原因估计也是因为调整了这个默认值解决了问题？
@arm64v8a
