### ISSUE TITLE
BUG: Hysteria 2节点无法使用Google服务

### ISSUE THREAD

**Issue by JackoChenWei** [MatsuriDayo/NekoBoxForAndroid#795]
Hysteria 2协议节点无法访问Google Translate, Gmail, Google Lens, Play Store等Google服务，具体表现为页面一直在加载、网络未连接。但其他协议节点就可正常访问。大概是客户端问题，Clash Meta For Android连接同样的Hysteria 2协议节点就可正常访问。

**Comment by MOMOSOR** [comment]
用clash verge
