### ISSUE TITLE
Which is the best?

### ISSUE THREAD

**Issue by kaiminz** [MatsuriDayo/NekoBoxForAndroid#8]
Matsuri, or NekoBox which one shall we prefer in use?

**Comment by nimbold** [comment]
In my current testings Nekobox is better for V2ray connections especially VLess ones. It doesn't need any plugin and has a stable connection.
The only downside is that currently SSH doesn't work in NekoBox (at least for me).

**Comment by kaiminz** [comment]
Thanks for your solving the puzzle.
