### ISSUE TITLE
BUG: 1.3.3版本的hy节点端口跳跃配置不生效(导致无法联通节点)

### ISSUE THREAD

**Issue by moranno** [MatsuriDayo/NekoBoxForAndroid#827]
## 1.3.3版本中的hy节点端口跳跃配置不生效，会导致节点不通；**在1.3.2及以下版本正常**。
<img width="463" alt="image" src="https://github.com/user-attachments/assets/e6f96f5b-7178-45ba-8fa0-06595a53d871" />
<img width="459" alt="image" src="https://github.com/user-attachments/assets/388ea625-bea8-4b66-ba4c-6585729ad02e" />

----------

## 如果删除端口跳跃配置，测试正常：

<img width="460" alt="image" src="https://github.com/user-attachments/assets/54d2e268-83a2-4bf1-92be-f378f4a798c3" />
<img width="466" alt="image" src="https://github.com/user-attachments/assets/12a241b4-75af-49aa-a002-af27fbc0f542" />

Actual behavior:

**在1.3.2及以下版本正常**。

## How to reproduce

1.3.3版本中填写hy节点的端口范围 5000-6000，点击下方链接图标，然后，”点击此此处测试链接“

## log

尝试过打开日志，但无法获取到

**Comment by KGB333** [comment]
确认有同样的问题

**Comment by KGB333** [comment]
添加了绕过可以使用，感觉应该是bug？更新前确实不需要设置绕过> 尝试把节点的域名加到 路由-绕过 规则？

**Comment by KGB333** [comment]
> 尝试把节点的域名加到 路由-绕过 规则？

添加了bypass可以使用，应该是bug？更新前确实不需要设置绕过

**Comment by IAMIBM** [comment]
> > 尝试把节点的域名加到 路由-绕过 规则？
> 
> 添加了bypass可以使用，应该是bug？更新前确实不需要设置绕过

新建了一个绕过规则，不过看起来没有起作用。请教，您是如何添加的？
