### ISSUE TITLE
The url test does not work.

### ISSUE THREAD

**Issue by EndermanCo** [MatsuriDayo/NekoBoxForAndroid#85]
Hello
As for the configs, half of ws is half of grpc.
And all configs have alpn h2.
The problem is that they time out when taking the url test while it works in another program.
log:
[NB4A 2683567986474120298.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/11191101/NB4A.2683567986474120298.log)
tip:The configs have tls 1.3 and work with it.

**Comment by EndermanCo** [comment]
it can connect but it wont actually work (these configs are working via v2rayNG/v2flyNG apps though)
When connecting, it gives this error when testing:
failed: Get "http://cp.cloudflare.com" unknown version: 80
because its on a private server i cannot share my exact configs, but here's the config i just removed the domain names from it
config:
[Tronjan GRPC WS TLS CDN.txt](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/11211533/Tronjan.GRPC.WS.TLS.CDN.txt)

**Comment by zoheirkabuli** [comment]
I have the same issue

**Comment by zoheirkabuli** [comment]
With the both vless and grpc
Alpn: h2 and http/1.1
Fingerprint: chrome and Firefox

**Comment by Ght55** [comment]
Not connected very bad app nekobox 
Matsuri perfect 
Matsuri  on project  Vless  ✅️

**Comment by EndermanCo** [comment]
> Not connected very bad app nekobox Matsuri perfect Matsuri on project Vless ✅️

Please do not spam. Go raise your problem instead of spamming.
